CREATE TABLE IF NOT EXISTS guilds (
	id BIGINT NOT NULL PRIMARY KEY,
	name VARCHAR(35) NOT NULL,
	owner BIGINT NOT NULL REFERENCES charinfo(id),
	motd TEXT,
	uscore INT NOT NULL DEFAULT 0,
	created BIGINT UNSIGNED NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS guild_members (
	guild_id BIGINT NOT NULL REFERENCES guilds(id),
	character_id BIGINT NOT NULL REFERENCES charinfo(id),
	rank INT NOT NULL DEFAULT 4,
	joined BIGINT UNSIGNED NOT NULL DEFAULT 0
);
