ALTER TABLE leaderboard 
    ADD COLUMN hitPercentage FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN streak INT NOT NULL DEFAULT 0,
    ADD COLUMN bestLapTime FLOAT NOT NULL DEFAULT 0,
    ADD COLUMN numWins INT NOT NULL DEFAULT 0,
    ADD COLUMN timesPlayed INT NOT NULL DEFAULT 0,
    MODIFY time FLOAT NOT NULL DEFAULT 0;

ALTER TABLE leaderboard CHANGE time bestTime float;
ALTER TABLE leaderboard CHANGE last_played last_played TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP();

UPDATE leaderboard SET streak = bestTime where game_id = 1864;
