name: Performance Issue
description: Report slow performance or memory issues when running DarkflameServer
title: "PERF: "
labels: ["performance", "triage"]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: "Make sure you've done the following:"
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.
          required: true
  - type: input
    id: server-version
    attributes:
      label: DarkflameServer Version
      description: >
        DarkflameServer version or commit SHA (can be obtained with `git rev-parse --short HEAD`)
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: >
        Please include the environment you're running DarkflameServer on (for example: Windows, macOS, Ubuntu, WSL, etc), available memory, number of CPU cores.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please provide a minimal, example that quantifies slow runtime or memory issues. 
        Ideally include screenshots of CPU usage or memory usage. And if possible point
        to the code that you may suspect to cause the issue.
    validations:
      required: true
  - type: textarea
    id: prior-performance
    attributes:
      label: Prior Performance
      description: >
        If applicable, please provide the prior version of DarkflameServer and output
        of the same reproducible example where the performance issue did not exist.
