#pragma once

#ifndef EADDFRIENDRESPONSETYPE_H
#define EADDFRIENDRESPONSETYPE_H

#include <cstdint>

enum class eAddFriendResponseType : uint8_t {
	ACCEPTED = 0,
	ALREADYFRIEND,
	INVALIDCHARACTER,
	GENERALERROR,
	YOURFRIENDSLISTFULL,
	THEIRFRIENDLISTFULL,
	DECLINED,
	BUSY,
	NOTONLINE,
	WAITINGAPPROVAL,
	MYTHRAN,
	CANCELLED,
	FRIENDISFREETRIAL
};

#endif  //!EADDFRIENDRESPONSETYPE_H
