#ifndef __ECHATMESSAGERESPONSECODES__H__
#define __ECHATMESSAGERESPONSECODES__H__

#include <cstdint>
enum class eChatMessageResponseCode : uint8_t {
	SENT = 0,
	NOTONLINE,
	GENERALERROR,
	RECEIVEDNEWWHISPER,
	NOTFRIENDS,
	SENDERFREETRIAL,
	RECEIVERFREETRIAL,
};

#endif  //!__ECHATMESSAGERESPONSECODES__H__