#ifndef ECHATMESSAGERESPONSECODE_H
#define ECHATMESSAGERESPONSECODE_H

#include <cstdint>

enum class eChatMessageResponseCode : uint8_t {
	SENT = 0,
	NOTONLINE,
	GENERALERROR,
	RECEIVEDNEWWHISPER,
	NOTFRIENDS,
	SENDERFREETRIAL,
	RECEIVERFREETRIAL,
};

#endif // ECHATMESSAGERESPONSECODE_H
