#ifndef ECHARACTERCREATIONRESPONSE_H
#define ECHARACTERCREATIONRESPONSE_H

#include <cstdint>

enum class eCharacterCreationResponse : uint8_t {
	SUCCESS = 0,
	OBJECT_ID_UNAVAILABLE,
	NAME_NOT_ALLOWED,
	PREDEFINED_NAME_IN_USE,
	CUSTOM_NAME_IN_USE
};

#endif  //!ECHARACTERCREATIONRESPONSE_H
