
#ifndef __EHELPTYPE__H__
#define __EHELPTYPE__H__

#include <cstdint>

enum class eHelpType : int32_t {
	NONE = 0,
	UNLOCK_MINIMAP = 2,
	TOGGLETOOLTIP_OUTOFTIME_REBUILD = 3,
	TOGGLETOOLTIP_LEAVELOSE_REBUILD = 4,
	TOGGLECONTROLSTUTORIAL_WALKING = 6,
	DISPLAYTUTORIAL_PASSPORT_1ST_SMASH = 7,
	TOOLTIP_1ST_IMAGINATION_PICKUP = 8,
	UNKNOWN9 = 9,
	PETTAMINGMINIGAME_TUTORIAL_01 = 15,
	PR_BOUNCER_TUTORIAL_03 = 16,
	PR_TOOLTIP_1ST_PET_JUMPED_ON_SWITCH = 17,
	PR_DIG_TUTORIAL_01 = 18,
	PR_DIG_TUTORIAL_03 = 19,
	PR_BOUNCER_TUTORIAL_01 = 20,
	PR_NO_IMAGINATION_HIBERNATE = 21,
	UNKNOWN22 = 22,
	TOGGLECONTROLSTUTORIAL_JUMPING = 26,
	TOGGLECONTROLSTUTORIAL_DOUBLEJUMPING = 27,
	TOGGLECONTROLSTUTORIAL_CAMERA = 28,
	TOGGLECONTROLSTUTORIAL_SMASH = 30,
	UNKNOWN38 = 38,
	UI_MOD_BUILD_PUT_ON_HAT = 40,
	UI_MOD_BUILD_EQUIP_FIRST_MODULE = 41,
	UNKNOWN42 = 42,
	UNKNOWN43 = 43,
	UI_MOD_BUILD_GO_LAUNCH_ROCKET = 44,
	UI_MOD_BUILD_TALK_TO_SKYLANE = 45,
	UNKNOWN53 = 53,
	PET_DESPAWN_BY_OWNER_HIBERNATE = 69,
	PET_DESPAWN_TAMING_NEW_PET = 70,
	UI_INVENTORY_FULL_CANNOT_PICKUP_ITEM = 86
};

#endif  //!__EHELPTYPE__H__
