#ifndef __ELOGINRESPONSE__H__
#define __ELOGINRESPONSE__H__

#include <cstdint>

enum class eLoginResponse : uint8_t {
	GENERAL_FAILED = 0,
	SUCCESS,
	BANNED,
	// Unused 3
	// Unused 4
	PERMISSIONS_NOT_HIGH_ENOUGH = 5,
	INVALID_USER,
	ACCOUNT_LOCKED,
	WRONG_PASS,
	ACCOUNT_ACTIVATION_PENDING,
	ACCOUNT_DISABLED,
	GAME_TIME_EXPIRED,
	FREE_TRIAL_ENDED,
	PLAY_SCHEDULE_TIME_UP,
	ACCOUNT_NOT_ACTIVATED
};

#endif  //!__ELOGINRESPONSE__H__
