#ifndef EPROPERTYSORTTYPE_H
#define EPROPERTYSORTTYPE_H

enum ePropertySortType : int32_t {
	SORT_TYPE_FRIENDS = 0,
	SORT_TYPE_REPUTATION = 1,
	SORT_TYPE_RECENT = 3,
	SORT_TYPE_FEATURED = 5
};

#endif  //!EPROPERTYSORTTYPE_H
