#ifndef EQUICKBUILDFAILREASON_H
#define EQUICKBUILDFAILREASON_H

#include <cstdint>

enum class eQuickBuildFailReason : uint32_t {
	NOT_GIVEN,
	OUT_OF_IMAGINATION,
	CANCELED_EARLY,
	BUILD_ENDED
};

#endif  //!EQUICKBUILDFAILREASON_H
