#pragma once

#ifndef __ERACINGTASKPARAM__H__
#define __ERACINGTASKPARAM__H__

#include <cstdint>

enum class eRacingTaskParam : int32_t {
	FINISH_WITH_PLACEMENT = 1,
	LAP_TIME,
	TOTAL_TRACK_TIME,
	COMPLETE_ANY_RACING_TASK,
	COMPLETE_TRACK_TASKS,
	MODULAR_BUILDING,
	SAFE_DRIVER = 10,
	SMASHABLES,
	COLLECT_IMAGINATION,
	COMPETED_IN_RACE,
	WIN_RACE_IN_WORLD,
	FIRST_PLACE_MULTIPLE_TRACKS,
	LAST_PLACE_FINISH,
	SMASH_SPECIFIC_SMASHABLE
};

#endif  //!__ERACINGTASKPARAM__H__
