#ifndef __EREPONSEMOVEITEMBETWEENINVENTORYTYPECODE__H__
#define __EREPONSEMOVEITEMBETWEENINVENTORYTYPECODE__H__

#include <cstdint>

enum class eReponseMoveItemBetweenInventoryTypeCode : int32_t {
	SUCCESS,
	FAIL_GENERIC,
	FAIL_INV_FULL,
	FAIL_ITEM_NOT_FOUND,
	FAIL_CANT_MOVE_TO_THAT_INV_TYPE,
	FAIL_NOT_NEAR_BANK,
	FAIL_CANT_SWAP_ITEMS,
	FAIL_SOURCE_TYPE,
	FAIL_WRONG_DEST_TYPE,
	FAIL_SWAP_DEST_TYPE,
	FAIL_CANT_MOVE_THINKING_HAT,
	FAIL_DISMOUNT_BEFORE_MOVING
};

#endif  //!__EREPONSEMOVEITEMBETWEENINVENTORYTYPECODE__H__
