#ifndef __ESERVERDISCONNECTIDENTIFIERS__H__
#define __ESERVERDISCONNECTIDENTIFIERS__H__

#include <cstdint>

enum class eServerDisconnectIdentifiers : uint32_t {
	UNKNOWN_SERVER_ERROR = 0,
	WRONG_GAME_VERSION,
	WRONG_SERVER_VERSION,
	CONNECTION_ON_INVALID_PORT,
	DUPLICATE_LOGIN,
	SERVER_SHUTDOWN,
	SERVER_MAP_LOAD_FAILURE,
	INVALID_SESSION_KEY,
	ACCOUNT_NOT_IN_PENDING_LIST,
	CHARACTER_NOT_FOUND,
	CHARACTER_CORRUPTED,
	KICK,
	SAVE_FAILURE,
	FREE_TRIAL_EXPIRED,
	PLAY_SCHEDULE_TIME_DONE
};

#endif  //!__ESERVERDISCONNECTIDENTIFIERS__H__
