#if (!defined(__EWORLDMESSAGETYPE__H__) || defined(GENERATE_ENUM_STRINGS))

#if (!defined(__EWORLDMESSAGETYPE__H__))
	#define __EWORLDMESSAGETYPE__H__
#endif

#include <cstdint>
#include "StringifyEnums.h"

BEGIN_ENUM_WITH_VALUES(eWorldMessageType, uint32_t)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(VALIDATION, 1)  // 				Session info
	DECLARE_ENUM_ELEMENT_WITH_VALUE(CHARACTER_LIST_REQUEST, 2)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(CHARACTER_CREATE_REQUEST, 3)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(LOGIN_REQUEST, 4)  // 			Character selected
	DECLARE_ENUM_ELEMENT_WITH_VALUE(GAME_MSG, 5)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(CHARACTER_DELETE_REQUEST, 6)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(CHARACTER_RENAME_REQUEST, 7)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(HAPPY_FLOWER_MODE_NOTIFY, 8)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(SLASH_RELOAD_MAP, 9)  // 			Reload map cmp
	DECLARE_ENUM_ELEMENT_WITH_VALUE(SLASH_PUSH_MAP_REQUEST, 10)  // 	Push map req cmd
	DECLARE_ENUM_ELEMENT_WITH_VALUE(SLASH_PUSH_MAP, 11)  // 			Push map cmd
	DECLARE_ENUM_ELEMENT_WITH_VALUE(SLASH_PULL_MAP, 12)  // 			Pull map cmd
	DECLARE_ENUM_ELEMENT_WITH_VALUE(LOCK_MAP_REQUEST, 13)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(GENERAL_CHAT_MESSAGE, 14)  // 		General chat message
	DECLARE_ENUM_ELEMENT_WITH_VALUE(HTTP_MONITOR_INFO_REQUEST, 15)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(SLASH_DEBUG_SCRIPTS, 16)  // 		Debug scripts cmd
	DECLARE_ENUM_ELEMENT_WITH_VALUE(MODELS_CLEAR, 17)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(EXHIBIT_INSERT_MODEL, 18)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(LEVEL_LOAD_COMPLETE, 19)  // 		Character data request
	DECLARE_ENUM_ELEMENT_WITH_VALUE(TMP_GUILD_CREATE, 20)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(ROUTE_PACKET, 21)  // 				Social?
	DECLARE_ENUM_ELEMENT_WITH_VALUE(POSITION_UPDATE, 22)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(MAIL, 23)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(WORD_CHECK, 24) // 				Whitelist word check
	DECLARE_ENUM_ELEMENT_WITH_VALUE(STRING_CHECK, 25)  // 				Whitelist string check
	DECLARE_ENUM_ELEMENT_WITH_VALUE(GET_PLAYERS_IN_ZONE, 26)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(REQUEST_UGC_MANIFEST_INFO, 27)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(BLUEPRINT_GET_ALL_DATA_REQUEST, 28)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(CANCEL_MAP_QUEUE, 29)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(HANDLE_FUNNESS, 30)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(FAKE_PRG_CSR_MESSAGE, 31)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(REQUEST_FREE_TRIAL_REFRESH, 32)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(GM_SET_FREE_TRIAL_STATUS, 33)
	DECLARE_ENUM_ELEMENT_WITH_VALUE(UI_HELP_TOP_5, 91)
END_ENUM_WITH_VALUES(eWorldMessageType, uint32_t)

#endif  //!__EWORLDMESSAGETYPE__H__
