#if (!defined(__EWORLDMESSAGETYPE__H__) || defined(GENERATE_ENUM_STRINGS))

#if (!defined(__EWORLDMESSAGETYPE__H__))
	#define __EWORLDMESSAGETYPE__H__
#endif

#include <cstdint>
#include "StringifiedEnum.h"

BEGIN_STRINGIFIED_ENUM(eWorldMessageType, uint32_t)
	STRINGIFIED_ENUM_ENTRY(VALIDATION, 1)  // 					Session info
	STRINGIFIED_ENUM_ENTRY(CHARACTER_LIST_REQUEST, 2)
	STRINGIFIED_ENUM_ENTRY(CHARACTER_CREATE_REQUEST, 3)
	STRINGIFIED_ENUM_ENTRY(LOGIN_REQUEST, 4)  // 				Character selected
	STRINGIFIED_ENUM_ENTRY(GAME_MSG, 5)
	STRINGIFIED_ENUM_ENTRY(CHARACTER_DELETE_REQUEST, 6)
	STRINGIFIED_ENUM_ENTRY(CHARACTER_RENAME_REQUEST, 7)
	STRINGIFIED_ENUM_ENTRY(HAPPY_FLOWER_MODE_NOTIFY, 8)
	STRINGIFIED_ENUM_ENTRY(SLASH_RELOAD_MAP, 9)  // 			Reload map cmp
	STRINGIFIED_ENUM_ENTRY(SLASH_PUSH_MAP_REQUEST, 10)  // 		Push map req cmd
	STRINGIFIED_ENUM_ENTRY(SLASH_PUSH_MAP, 11)  // 				Push map cmd
	STRINGIFIED_ENUM_ENTRY(SLASH_PULL_MAP, 12)  // 				Pull map cmd
	STRINGIFIED_ENUM_ENTRY(LOCK_MAP_REQUEST, 13)
	STRINGIFIED_ENUM_ENTRY(GENERAL_CHAT_MESSAGE, 14)  // 		General chat message
	STRINGIFIED_ENUM_ENTRY(HTTP_MONITOR_INFO_REQUEST, 15)
	STRINGIFIED_ENUM_ENTRY(SLASH_DEBUG_SCRIPTS, 16)  // 		Debug scripts cmd
	STRINGIFIED_ENUM_ENTRY(MODELS_CLEAR, 17)
	STRINGIFIED_ENUM_ENTRY(EXHIBIT_INSERT_MODEL, 18)
	STRINGIFIED_ENUM_ENTRY(LEVEL_LOAD_COMPLETE, 19)  // 		Character data request
	STRINGIFIED_ENUM_ENTRY(TMP_GUILD_CREATE, 20)
	STRINGIFIED_ENUM_ENTRY(ROUTE_PACKET, 21)  // 				Social?
	STRINGIFIED_ENUM_ENTRY(POSITION_UPDATE, 22)
	STRINGIFIED_ENUM_ENTRY(MAIL, 23)
	STRINGIFIED_ENUM_ENTRY(WORD_CHECK, 24) // 					Whitelist word check
	STRINGIFIED_ENUM_ENTRY(STRING_CHECK, 25)  // 				Whitelist string check
	STRINGIFIED_ENUM_ENTRY(GET_PLAYERS_IN_ZONE, 26)
	STRINGIFIED_ENUM_ENTRY(REQUEST_UGC_MANIFEST_INFO, 27)
	STRINGIFIED_ENUM_ENTRY(BLUEPRINT_GET_ALL_DATA_REQUEST, 28)
	STRINGIFIED_ENUM_ENTRY(CANCEL_MAP_QUEUE, 29)
	STRINGIFIED_ENUM_ENTRY(HANDLE_FUNNESS, 30)
	STRINGIFIED_ENUM_ENTRY(FAKE_PRG_CSR_MESSAGE, 31)
	STRINGIFIED_ENUM_ENTRY(REQUEST_FREE_TRIAL_REFRESH, 32)
	STRINGIFIED_ENUM_ENTRY(GM_SET_FREE_TRIAL_STATUS, 33)
	STRINGIFIED_ENUM_ENTRY(UI_HELP_TOP_5, 91)
END_STRINGIFIED_ENUM(eWorldMessageType, uint32_t)

#endif  //!__EWORLDMESSAGETYPE__H__
